
version: '2'
services:
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  
  kafka:
    image: wurstmeister/kafka 
    ports:
      - 9092:9092
    environment:
      KAFKA_PORT: 9092
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: "${DOCKERHOST}"
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://${DOCKERHOST}:9092"
      KAFKA_ZOOKEEPER_CONNECT: "${DOCKERHOST}:2181"
      KAFKA_CREATE_TOPICS: "t1:3:2"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  test_producer:
    image: test_producer
    build:
      context: ./test_producer
      dockerfile: Dockerfile
    depends_on: 
      - kafka 

  test_consumer:
    image: test_consumer
    build:
      context: ./test_consumer
      dockerfile: Dockerfile
    depends_on: 
      - kafka 